client.c File Reference
This file implements a `very` simple sample client.
#include <errno.h>
*
#include <stdio.h>
*
#include <time.h>
*
#include <string.h>
*
#include `storage.h`
*
Macros
#define SERVERHOST `localhost`
#define SERVERPORT 1111
#define SERVERUSERNAME `admin`
#define SERVERPASSWORD `dog4sale`
#define TABLE `marks`
#define KEY `ece297`
#define LENGTH 50
#define LOGGING 2
Functions
int main (int argc, char *argv[])
Start a client to interact with the storage server.
Variables
FILE * log
Detailed Description
This file implements a `very` simple sample client. The client connects to the server, running at SERVERHOST:SERVERPORT and performs a number of storage_* operations. If there are errors, the client exists.
Definition in file client.c.
Function Documentation
int main (int argc, char * argv[])
Start a client to interact with the storage server.
If connect is successful, the client performs a storage_set/get() on TABLE and KEY and outputs the results on stdout. Finally, it exists after disconnecting from the server.
Definition at line 34 of file client.c.
References storage_auth(), storage_connect(), storage_disconnect(), storage_get(), storage_set(), and storage_record::value.